version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://localhost:4000

  admin:
    build: ./admin
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: